name: CT-MRI Backlog Alert (Vision)
on:
  schedule:
    # Run hourly; the script enforces your ET windows (6/8/10p M–F; Sat 4a→10p q2h)
    - cron: "0 * * * *"
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium
      - name: Check backlog (GPT Vision)
        env:
          AVR_USER: ${{ secrets.AVR_USER }}
          AVR_PASS: ${{ secrets.AVR_PASS }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          # ---- Configurable knobs ----
          THRESHOLD: "25"
          AGE_MINUTES: "60"
          SITE_LABEL: "Baptist Health Corbin (AVR)"
          OPENAI_VISION_MODEL: "gpt-4o-mini"
          # Set DRY_RUN=true in repo secrets to validate for a day
          DRY_RUN: ${{ secrets.DRY_RUN }}
        run: python check_backlog_gpt.py
